# Site settings
title: Learn How to Code with Tsara
email: tsara.tf@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tsara27.github.io" # the base hostname & protocol for your site
twitter_username: tsara_tf
github_username:  tsara27
linkedin_username: tsara-sudrajat
facebook_username: tsara.tf
google_plus_username: +TsaraFatmaLarasatiSudrajat
linkedin_username: tsara-sudrajat

# Build settings
markdown: kramdown
