# Site settings
title: Learn How to Code with Tsara
email: tsara.tf@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  How te get started with Ruby, Ruby on Rails tutorials, IT stuff and her thoughts by Tsara Fatma Larasati Sudrajat.
keywords:
  - ruby
  - ruby on rails
  - html
  - css
  - tutorials
  - tutorial
  - practice
  - guide
  - blog
baseurl: "" # the subpath of your site, e.g. /blog/

tag_page_layout: tags
tag_page_dir: tags
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

url: "http://tsara27.github.io" # the base hostname & protocol for your site
twitter_username: tsara_tf
github_username:  tsara27
linkedin_username: tsara-sudrajat
facebook_username: tsara.tf
google_plus_username: +TsaraFatmaLarasatiSudrajat
linkedin_username: tsarasudrajat

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: <!--more-->

gems:
  - jekyll-sitemap